import { Broker, Contact, EquityRelease, Note, RetirementIncome } from "@workspace/api-client-react";

export const MOCK_BROKERS: Broker[] = [
  {
    id: 1,
    ifaRef: "IFA1001",
    brokerNo: "BRK-001",
    fimbraNo: "FIM-992",
    brokerName: "First Class Financial",
    tradingName: "FCF Partners",
    addressLine1: "123 Wealth Avenue",
    addressLine2: "Suite 4B",
    town: "London",
    county: "Greater London",
    postcode: "EC1A 1BB",
    telephone: "020 7123 4567",
    fax: "020 7123 4568",
    email: "contact@firstclassfin.co.uk",
    initials: "FCF",
    dateChecked: "2023-10-15",
    fcaReference: "FCA77621",
    annuityToba: true,
    status: "Active",
    sentDate: "2022-01-10",
    grade: "National Accounts",
    nextDiaryDate: "2024-05-20",
    ifaMemberNo: "MEM-8821",
    brokerManager: "Sarah Jenkins",
    keyAccount: "Gold",
    partnerCode: "PTN-01",
    region: "South East",
    createdBy: "admin",
    createdDate: "2020-05-01",
    amendedBy: "jdoe",
    amendedDate: "2023-11-02",
  },
  {
    id: 2,
    ifaRef: "IFA1002",
    brokerNo: "BRK-042",
    fimbraNo: "FIM-114",
    brokerName: "Apex Wealth Management",
    tradingName: "Apex",
    addressLine1: "45 Pinnacle Way",
    town: "Manchester",
    county: "Lancashire",
    postcode: "M1 2AB",
    telephone: "0161 987 6543",
    email: "info@apexwealth.co.uk",
    fcaReference: "FCA12345",
    annuityToba: false,
    status: "Active",
    grade: "Regional",
    brokerManager: "Tom Hanks",
    region: "North West",
  }
];

export const MOCK_CONTACTS: Contact[] = [
  {
    id: 101,
    brokerId: 1,
    reference: "CON-A1",
    title: "Mr",
    initials: "J",
    forename: "John",
    surname: "Smith",
    salutation: "John",
    position: "Senior Partner",
    addressLine1: "123 Wealth Avenue",
    town: "London",
    postcode: "EC1A 1BB",
    mobileTelephone: "07700 900123",
    emailAddress: "j.smith@firstclassfin.co.uk",
    paidByBacs: true,
    bankSortCode: "20-40-60",
    bankAccountNo: "12345678",
    bankAccountName: "First Class Financial Ltd",
    useNetworkTerms: false,
    defaultAdviceType: "Independent",
    defaultRemunerationBasis: "Fee",
    network: false,
    tiedAgent: false,
    isPrincipal: true,
  },
  {
    id: 102,
    brokerId: 1,
    reference: "CON-A2",
    title: "Ms",
    initials: "L",
    forename: "Laura",
    surname: "Davies",
    salutation: "Laura",
    position: "Compliance Officer",
    emailAddress: "l.davies@firstclassfin.co.uk",
    isPrincipal: false,
  }
];

export const MOCK_RETIREMENT: RetirementIncome = {
  id: 1,
  brokerId: 1,
  npaAdviserCharges: 1.5,
  npaAmount: 500,
  npaCommission: 2.0,
  npaExpenseDiscount: 0.5,
  npaMarketingAllowance: 100,
  pipaAdviserCharges: 1.0,
  pipaAmount: 250,
  pipaCommission: 1.5,
  prpAdviserCharges: 2.0,
  prpAmount: 1000,
  prpCommission: 3.0,
};

export const MOCK_EQUITY: EquityRelease = {
  id: 1,
  brokerId: 1,
  mortgagePermissions: true,
  erlmToba: true,
  flexibleBrokerRate: 1.25,
  flexibleMinimumAmount: 10000,
  flexibleNetworkRate: 0.25,
  flexibleTrailCommission: true,
  lumpSumBrokerRate: 1.50,
  lumpSumMinimumAmount: 15000,
  lumpSumNetworkRate: 0.30,
  packagingFee: 295,
  applicationFee: 99,
  ltvPercent: 50,
};

export const MOCK_NOTES: Note[] = [
  {
    id: 1,
    brokerId: 1,
    noteType: "SYS",
    description: "Status changed to Active",
    oldValue: "Pending",
    newValue: "Active",
    updatedBy: "System",
    updatedDate: "2023-10-15T10:30:00Z",
  },
  {
    id: 2,
    brokerId: 1,
    noteType: "USR",
    description: "Updated contact details for John Smith",
    oldValue: "",
    newValue: "New mobile added",
    updatedBy: "admin",
    updatedDate: "2023-11-02T14:45:00Z",
  }
];
