import { pgTable, serial, text, boolean, numeric, timestamp } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

export const brokersTable = pgTable("brokers", {
  id: serial("id").primaryKey(),
  ifaRef: text("ifa_ref"),
  brokerNo: text("broker_no"),
  fimbraNo: text("fimbra_no"),
  brokerName: text("broker_name").notNull(),
  tradingName: text("trading_name"),
  addressLine1: text("address_line1"),
  addressLine2: text("address_line2"),
  building: text("building"),
  noStreet: text("no_street"),
  district: text("district"),
  city: text("city"),
  town: text("town"),
  county: text("county"),
  postcode: text("postcode"),
  telephone: text("telephone"),
  fax: text("fax"),
  email: text("email"),
  initials: text("initials"),
  dateChecked: text("date_checked"),
  fcaReference: text("fca_reference"),
  annuityToba: boolean("annuity_toba").default(false),
  status: text("status").default("Active"),
  sentDate: text("sent_date"),
  grade: text("grade"),
  nextDiaryDate: text("next_diary_date"),
  ifaMemberNo: text("ifa_member_no"),
  brokerManager: text("broker_manager"),
  keyAccount: text("key_account"),
  partnerCode: text("partner_code"),
  region: text("region"),
  salutation: text("salutation"),
  classCode: text("class_code"),
  repkey: text("repkey"),
  rsmNo: text("rsm_no"),
  nextIfaIllRef: text("next_ifa_ill_ref"),
  sibReference: text("sib_reference"),
  sibAuthorisationDate: text("sib_authorisation_date"),
  sibInitials: text("sib_initials"),
  brokerPackSent: text("broker_pack_sent"),
  brokerPackSentDate: text("broker_pack_sent_date"),
  area: text("area"),
  nextContactNo: text("next_contact_no"),
  consultant: text("consultant"),
  peverelBroker: text("peverel_broker"),
  paidByBacs: text("paid_by_bacs"),
  bankSortCode: text("bank_sort_code"),
  bankAccountNo: text("bank_account_no"),
  bankAccountName: text("bank_account_name"),
  bankRef: text("bank_ref"),
  networkIfaReference: text("network_ifa_reference"),
  ifaCommission: text("ifa_commission"),
  networkCommission: text("network_commission"),
  network: text("network"),
  memberNumber: text("member_number"),
  plaIfaCommission: text("pla_ifa_commission"),
  plaNetworkCommission: text("pla_network_commission"),
  ifaWhen: text("ifa_when"),
  ifaPortfolio: text("ifa_portfolio"),
  brokerNameUpper: text("broker_name_upper"),
  expense: text("expense"),
  coCode: text("co_code"),
  ltcCommission: text("ltc_commission"),
  acareCommission: text("acare_commission"),
  namId: text("nam_id"),
  ilaCommission: text("ila_commission"),
  ilaExpense: text("ila_expense"),
  ifaIlaCommissionPct: text("ifa_ila_commission_pct"),
  ifaIlaExpensePct: text("ifa_ila_expense_pct"),
  networkIlaCommissionPct: text("network_ila_commission_pct"),
  icfpCommission: text("icfp_commission"),
  icfpExpense: text("icfp_expense"),
  networkIcfpCommissionPct: text("network_icfp_commission_pct"),
  createdBy: text("created_by"),
  createdDate: text("created_date"),
  amendedBy: text("amended_by"),
  amendedDate: text("amended_date"),
});

export const insertBrokerSchema = createInsertSchema(brokersTable).omit({ id: true });
export type InsertBroker = z.infer<typeof insertBrokerSchema>;
export type Broker = typeof brokersTable.$inferSelect;
